In [6]:
import numpy as np
a=np.array([1,2,3,4,5])

In [7]:
print(a)

[1 2 3 4 5]


In [8]:
b=np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [9]:
c=np.array([[[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]]])
print(c)

[[[[1 2 3]
   [4 5 6]]

  [[1 2 3]
   [4 5 6]]]]


In [10]:
import numpy as np
a=np.array([1,2,3])
print(a.dtype)

int64


In [11]:
bike=np.array(['ktm','royalenfield','scooty'])
print(bike.dtype)

<U12


In [12]:
b=np.array([[1,2,3],[4,5,6]])
print(b.dtype)

int64


In [13]:
w=np.array(['True','False'])
print(w.dtype)

<U5


In [4]:
import pandas as pd
data=pd.read_csv(r"C:\Users\vn229\OneDrive\ドキュメント\toptech\Student.1csv.csv")
print(data)

      S.NO         NAME   AGE  GENDER PASS/FAIL  MARKS PERFORMANCE  CGPA  \
0      1.0  Gokul Patel  20.0  Female      Pass   68.0     Average   6.8   
1      2.0       Om Raj  22.0  Female      Pass   64.0     Average   6.4   
2      3.0    Uday Nair  22.0    Male      Pass   92.0   Excellent   9.2   
3      4.0       Om Ali  21.0    Male      Pass   92.0   Excellent   9.2   
4      5.0    Jaya Sree  20.0  Female      Pass   71.0        Good   7.1   
..     ...          ...   ...     ...       ...    ...         ...   ...   
96    97.0        RICKY  20.0    Male      Fail   21.0   very poor   4.0   
97    98.0        SONA   20.0  Female      Fail   20.0   very poor   4.0   
98    99.0         MONA  20.0  Female      Fail   12.0   very poor   4.0   
99   100.0      DHARSHA  20.0    Male      Fail   11.0   very poor   4.0   
100    NaN          NaN   NaN     NaN       NaN    NaN         NaN   NaN   

         DEGREE                       COURSE ATTENDANCE  
0    IIT Madras  Introduction